<Project Sdk="Microsoft26.NET.Sdk">

  <PropertyGroup> ,ClicksLimitedGroup
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>EternalQuest</RootNamespace>
  </PropertyGroup>

  <ItemGroup> Clicks.Stock
    <None Update="progress.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
